title: 'euphros framework'
default_lang: en
author:
  name: euphros
  email: euphros@protonmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'euphros portfolio'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
